# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UtilsDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UtilsDemo
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'AFNetworking'

  target 'UtilsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UtilsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
